### ISSUE TITLE
gs:DownloadEstimator returns always true

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#119]
The DownloadEstimator process returns a positive response but the Download process hit the HARD limit.

The S-OSI product download will generate a 3.4Gb GeoTiff.
The hard limit is set to 1.4 Gb, but the estimator still allows the download.

See JIRA https://osgeo-org.atlassian.net/browse/GEOS-8925 and https://osgeo-org.atlassian.net/browse/GEOS-7230

This is currently mitigated by high download limits.

The following request will allow the download:
https://pastebin.com/WAbC0xFK

```
<wps:Output>
  <ows:Identifier>result</ows:Identifier>
  <ows:Title>Download Limits are respected or not!</ows:Title>
  <wps:Data>
    <wps:LiteralData>true</wps:LiteralData>
  </wps:Data>
</wps:Output>
```

The gs:download will start, but the process will end with an error:
https://pastebin.com/KYAjn1RH

```
2018-12-19 14:39:26,811 DEBUG [org.geoserver.wps.gs.download] - Download failed
2018-12-19 14:39:26,870 ERROR [org.geoserver.wps.executor] - Process execution failed
org.geotools.process.ProcessException: org.geotools.process.ProcessException: java.io.IOException: Download Exceeded the maximum HARD allowed size!
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:396)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:626)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:221)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:189)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.geotools.process.ProcessException: java.io.IOException: Download Exceeded the maximum HARD allowed size!
	at org.geoserver.wps.ppio.GeoTiffPPIO.encode(GeoTiffPPIO.java:109)
	at org.geoserver.wps.gs.download.RasterDownload.writeRaster(RasterDownload.java:839)
	at org.geoserver.wps.gs.download.RasterDownload.execute(RasterDownload.java:394)
	at org.geoserver.wps.gs.download.DownloadProcess.execute(DownloadProcess.java:301)
	... 12 more
Caused by: java.io.IOException: Download Exceeded the maximum HARD allowed size!
	at org.geoserver.wps.gs.download.RasterDownload$1.raiseError(RasterDownload.java:828)
	at org.geoserver.wps.gs.download.LimitedImageOutputStream.checkLimit(LimitedImageOutputStream.java:56)
	at org.geoserver.wps.gs.download.LimitedImageOutputStream.write(LimitedImageOutputStream.java:85)
	at it.geosolutions.io.output.adapter.OutputStreamAdapter.write(OutputStreamAdapter.java:62)
	at javax.imageio.stream.FileCacheImageOutputStream.flushBefore(FileCacheImageOutputStream.java:255)
	at javax.imageio.stream.ImageInputStreamImpl.flush(ImageInputStreamImpl.java:825)
	at org.geotools.gce.geotiff.GeoTiffWriter.writeImage(GeoTiffWriter.java:428)
	at org.geotools.gce.geotiff.GeoTiffWriter.write(GeoTiffWriter.java:259)
	at org.geoserver.wcs.responses.GeoTiffWriterHelper.write(GeoTiffWriterHelper.java:191)
	at org.geoserver.wps.ppio.GeoTiffPPIO.encode(GeoTiffPPIO.java:107)
	... 15 more
```

The current download.properties content is as follows:
```
maxFeatures=145000
rasterSizeLimits=128000000
writeLimits=64000000
hardOutputLimit=4000000000
#hardOutputLimit=1400000000
compressionLevel=8
maxAnimationFrames=1000
```

S-OSI NetCDF Mosaic Configuration contains sensitive information: https://docs.google.com/document/d/16XYbQhU8T7SkRLm8r8s8-G_IKUVeBPbBHiBG-kDqH6c/edit#

**Comment by Gnafu** [comment]
The fix now computes the actual size, so the limits has been modified to allow an 8000x8000 image, with 14 8-bytes bands.

```
maxFeatures=145000
rasterSizeLimits=128000000
writeLimits=7168000000
hardOutputLimit=6000000000
compressionLevel=8
maxAnimationFrames=1000
```
