### ISSUE TITLE
Timeout when trying to download full resolution product

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#188]
See email exchange with Lena.

**Comment by Gnafu** [comment]
I found out GeoServer is taking too long to send the response when it accepts an asynchronous WPS process.
It takes more than 60 seconds to answer "Process accepted." so the nginx kicks in and kills the request.

The WPS process goes on anyway, producing the correct output in the output directory, but no-one will ever be able to fetch the result, because the response with the processId gets lost.

I'm attaching the test request, the log and the jstack.
The test request will result in a process failure but that's not the point (the same issue occur in another environment where I don't have currently the power to run jstack)

[https://app.zenhub.com/files/102132334/d4d776fe-afc8-4c99-b98d-c2d922e4ee74/download](https://app.zenhub.com/files/102132334/d4d776fe-afc8-4c99-b98d-c2d922e4ee74/download)

**Comment by Gnafu** [comment]
This is still an issue with 2.16.x

**Comment by Gnafu** [comment]
@aaime I gathered the issue informations  and uploaded to dropbox (zenhub has a limit on file attachements): GeoSolutions/2019/EUMETSAT/C068-EUMETSAT-CGI-2019-WP1/issues/download_fails

It contains:
- The request content and curl command
- The GeoServer log
- The Jmap while the request is still running
- 120 Jstack (1 every second) while the request is running
- The WPS ouput folder content

**Comment by simboss** [comment]
@aaime can you look a this with priority?

Let me know...

**Comment by aaime** [comment]
Looking at it.

**Comment by aaime** [comment]
Here is what I'm seeing... each jstack seems to contain the exact same trace related to the download process, with GeoServer trying to open a file, and to do so, checking first if it exists (the file it the source URL of the coverage store):

```
"pool-16-thread-1" #740 prio=5 os_prio=0 tid=0x00007fd688022800 nid=0x7e4f runnable [0x00007fd5b27f7000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:819)
	at org.geoserver.platform.resource.Files$ResourceAdaptor.getType(Files.java:220)
	at org.geoserver.platform.resource.Resources.find(Resources.java:144)
	at org.geoserver.catalog.ResourcePool.getObjectToRead(ResourcePool.java:1652)
	at org.geoserver.catalog.ResourcePool.getGridCoverageReader(ResourcePool.java:1553)
	- locked <0x00000000ca27f940> (a org.geoserver.catalog.ResourcePool$CoverageHintReaderCache)
	at org.geoserver.catalog.ResourcePool.getGridCoverageReader(ResourcePool.java:1476)
	at org.geoserver.catalog.impl.CoverageInfoImpl.getGridCoverageReader(CoverageInfoImpl.java:157)
	at sun.reflect.GeneratedMethodAccessor507.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geoserver.catalog.impl.ModificationProxy.invoke(ModificationProxy.java:127)
	at com.sun.proxy.$Proxy40.getGridCoverageReader(Unknown Source)
	at org.geoserver.wms.MapLayerInfo.getCoverageReader(MapLayerInfo.java:301)
	at org.geoserver.wms.map.GetMapKvpRequestReader.read(GetMapKvpRequestReader.java:635)
	at org.geoserver.wps.gs.download.DownloadMapProcess.renderInternalLayer(DownloadMapProcess.java:542)
	at org.geoserver.wps.gs.download.DownloadMapProcess.buildImage(DownloadMapProcess.java:329)
	at org.geoserver.wps.gs.download.DownloadAnimationProcess.execute(DownloadAnimationProcess.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:628)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:224)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Checking the result anymation, it has 481 frames, and ``DownloadAnimationProcess.java:169`` is inside the loop building the images... meaning there is no way to know if we are just seeing the same loop advancing and stopping 481 times, taking each time some time to determine if the file exists, or if we are looking at just the first iteration... resource pool should be caching the reader, so the first seems more plausible.

Hum hum... however, two minutes to verify that a file/directory exist? I can undestand NFS being slow, but this seems too much?
I've noticed that there is another repeating trace keeping the file system busy:

```
"http-apr-8080-exec-22" #461 daemon prio=5 os_prio=0 tid=0x00007fd60000b000 nid=0x3f1a runnable [0x00007fd7305c8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:52)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.getType(FileSystemResourceStore.java:447)
	at org.geoserver.platform.FileWatcher.isModified(FileWatcher.java:92)
	at org.geoserver.security.PropertyFileWatcher.isStale(PropertyFileWatcher.java:49)
	at org.geoserver.flow.controller.IpBlacklistFilter.isBlackListed(IpBlacklistFilter.java:93)
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:79)
```

This code gets run when a request comes in, but no more than once per second.... how many blacklist filters are there in the control-flow configuration? Each one of them gets its own file watcher, so if I have 1000 black list filters, there are 1000 watchers (inefficient.... could it be the cause of this?Seems a bit of a stretch).

There  others that are also waiting on a "stat", checking existance of files:

```
"wcs111timerFactory-1" #99 daemon prio=5 os_prio=0 tid=0x00007fd6ca66c000 nid=0x85 runnable [0x00007fd6690f1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:52)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.getType(FileSystemResourceStore.java:447)
	at org.geoserver.wcs.response.WCSStorageCleaner.run(WCSStorageCleaner.java:36)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
"Timer-3" #102 daemon prio=5 os_prio=0 tid=0x00007fd6cac60000 nid=0x8c runnable [0x00007fd6684ef000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:52)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.getType(FileSystemResourceStore.java:447)
	at org.geoserver.platform.FileWatcher.isModified(FileWatcher.java:92)
	at org.geoserver.security.PropertyFileWatcher.isStale(PropertyFileWatcher.java:49)
	at org.geoserver.wps.gs.download.DownloadServiceConfigurationWatcher.run(DownloadServiceConfigurationWatcher.java:274)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

And the importer too:

```
"pool-22-thread-1" #97 prio=5 os_prio=0 tid=0x00007fd6ca472800 nid=0x7c runnable [0x00007fd669bf2000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:819)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.dir(FileSystemResourceStore.java:357)
	at org.geoserver.platform.GeoServerResourceLoader.findOrCreateDirectory(GeoServerResourceLoader.java:301)
	at org.geoserver.importer.Importer.getUploadRoot(Importer.java:1776)
	at org.geoserver.importer.job.JobQueue$2.run(JobQueue.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-20-thread-1" #96 prio=5 os_prio=0 tid=0x00007fd6ca471000 nid=0x7b runnable [0x00007fd669cf3000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:819)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.dir(FileSystemResourceStore.java:357)
	at org.geoserver.platform.GeoServerResourceLoader.findOrCreateDirectory(GeoServerResourceLoader.java:301)
	at org.geoserver.importer.Importer.getUploadRoot(Importer.java:1776)
	at org.geoserver.importer.job.JobQueue$2.run(JobQueue.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Doing a global count, I've found 6 threads trying to do file system checks, all apparently "running"... wondering if the data in question is in NFS and that it causing it to choke maybe?

Another possibility would be that the ResourcePool cache gets dropped at high rate, causing the caches to be dropped and files to be re-read... even a small delay for each file would pile up, with 481 frames to be generated. Do you know if there is anything making the GeoServer reset its configuration?

**Comment by simboss** [comment]
@aaime I have quickly read your analysis but it seems to me we are not looking for causes of the main issue we have which is:

> I found out GeoServer is taking too long to send the response when it accepts an asynchronous WPS process.
It takes more than 60 seconds to answer "Process accepted." so the nginx kicks in and kills the request.

Let's discuss this tomorrow with @Gnafu as well.

**Comment by aaime** [comment]
Discussed with Lorenzo, it came out that the request was not yet running when the first jstack was grabbed...  meaning the animator process execution underway in the first jstack (which reaches to stack 120) was already there, it was a previous call.

Starting from the second jstack we start seeing a request incoming, and blocked on control-flow:

 ```
"http-apr-8080-exec-22" #461 daemon prio=5 os_prio=0 tid=0x00007fd60000b000 nid=0x3f1a runnable [0x00007fd7305c8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:52)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.getType(FileSystemResourceStore.java:447)
	at org.geoserver.platform.FileWatcher.isModified(FileWatcher.java:92)
	at org.geoserver.security.PropertyFileWatcher.isStale(PropertyFileWatcher.java:49)
	at org.geoserver.flow.controller.IpBlacklistFilter.isBlackListed(IpBlacklistFilter.java:93)
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:79)
```

This request is stuck there until stack 120... I believe this is the request that Lorenzo actually sent, blocked on the flow controller checking if the configuration files have been changed.
I've checked, the IP blacklist filter makes one such call no matter how many IPs have been blocked.

If the above hyphotesis is correct, it explains much:

- Why in the logs we don't see the initial request processing, it did not really reach the WPS yet (requests details get logged when they hit a service object wrapper that does the logging)
- Why we don't get the asynch response back, it really hasn't reach the service, it's actually blocked in a servlet filter (the IP blacklist one)
- How the NFS being stuck can affect the asynch request (the relantionship that we were missing)

Given the control-flow periodically checks its config file date for updates, and it looks for it in the data directory, it would be best to move the data directory fully inside the local filesystem where GeoServer runs. That is also going to help other activities, like the WPS request logging and temporary response storage and the like, as they normally all happen inside the data dir (unless otherwise configured).

**Comment by simboss** [comment]
@Gnafu what do we do with this one? 

Can we close it?

**Comment by Gnafu** [comment]
Could not reproduce in the new environment and I did not received any report about this anymore.
