### ISSUE TITLE
IMGMT-311 WMS: Ingestion failed for all MSG 0DEG

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#339]
From Prasath:

Today, i tried to activate the continuous ingestion script for MSG 0DEG, just for a test of 5 minutes. The script pushes visualizations for most MSG 0DEG layers.

Apparently, every granule (+ the reltive JSON) is being immediately sent to quarantine. Could this be linked to the resolution of IMGMT-295. 

Some files are still in the quarantine, in case you want to test, and for the logs, look for the ingestion attempts of today. I also tried to investigate about the ingestion of one single file, and the relevant logs are attached.

[...]

I briefly checked for one Air mass sample

i receive the below error. Resembling the error reported in  IMGMT-295: WMS: Ingestion failed for Metop RGB 124

```
Created import session {import={data={file=/var/geoserver/data/LIC_FREE/msg_fes_rgb_airmass/MET10_RGBAirmass_PlateCarree_2005190930.tif, type=file}, targetStore={dataStore={name=rgb_airmass_fes}}, targetWorkspace={workspace={name=msg_fes}}}} at null

2020-05-19 12:04:07.400 +0000 [taskExecutor-2         :81a8eaa1-6a76-4dee-9226-5341c3775b75] ERROR org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl                 :

              GeoServer did not provide a URI for the import session

2020-05-19 12:04:07.415 +0000 [taskExecutor-2         :81a8eaa1-6a76-4dee-9226-5341c3775b75] ERROR org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl               :

              Ingestion of visualization "MET10_RGBAirmass_PlateCarree_2005190930.tif" failed after 199 ms. (Manifest path: /mnt/wms-data/polling/processing/wms-ingestion-manifest-generator-set-1/msg_airmass/MET10_RGBAirmass_PlateCarree_2005190930.properties)

org.eumetsat.eows.wms.ingservice.service.StorageException: No URI for import session

        at org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl.createImportSession(StorageServiceImpl.java:395)

        at org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl.store(StorageServiceImpl.java:280)

        at org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl.ingestVisualization(IngestionServiceImpl.java:117)

        at org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl.doIngestion(IngestionServiceImpl.java:85)

        at org.eumetsat.eows.wms.ingservice.service.queueingandexecution.QueueAndExecServiceImpl.lambda$submitIngestionTask$0(QueueAndExecServiceImpl.java:158)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

2020-05-19 12:04:07.415 +0000 [taskExecutor-2         :                                    ] WARN  org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl               :

              Unexpected exception occurred while ingesting visualization. (Manifest path: /mnt/wms-data/polling/processing/wms-ingestion-manifest-generator-set-1/msg_airmass/MET10_RGBAirmass_PlateCarree_2005190930.properties)

org.eumetsat.eows.wms.ingcommons.service.IngestionException: Ingestion failed

        at org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl.ingestVisualization(IngestionServiceImpl.java:123)

        at org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl.doIngestion(IngestionServiceImpl.java:85)

        at org.eumetsat.eows.wms.ingservice.service.queueingandexecution.QueueAndExecServiceImpl.lambda$submitIngestionTask$0(QueueAndExecServiceImpl.java:158)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

Caused by: org.eumetsat.eows.wms.ingservice.service.StorageException: No URI for import session

        at org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl.createImportSession(StorageServiceImpl.java:395)

        at org.eumetsat.eows.wms.ingservice.service.StorageServiceImpl.store(StorageServiceImpl.java:280)

        at org.eumetsat.eows.wms.ingservice.service.IngestionServiceImpl.ingestVisualization(IngestionServiceImpl.java:117)

        ... 6 more

```

**Comment by Gnafu** [comment]
Cannot reproduce on OPE
Waiting for additional feedback

**Comment by Gnafu** [comment]
Fabrizio Borgia 4:28 PM CEST (May 28)

Continuous ingestion ongoing for MSG 0DEG, MSG IODC, MSG RSS and METOP (selected layers). No issue so far.
