### ISSUE TITLE
Equi7Grid - Reprojection issue with Antartica

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#360]
https://cgi-pathfinders.atlassian.net/browse/IMGMT-368

![image](https://user-images.githubusercontent.com/5264230/91465679-5ce91280-e88e-11ea-8ea0-bcb09e9e0c50.png)

**Comment by randomorder** [comment]
Hi @aaime 
I deploye your latest fix on DEV but I am having issues with some of the projections. Most of them are working fine while for others I get exceptions:
![image](https://user-images.githubusercontent.com/5264230/91693613-94480f80-eb6b-11ea-8d56-798a4f972b7c.png)
![image](https://user-images.githubusercontent.com/5264230/91693619-97430000-eb6b-11ea-90fe-4299d737725e.png)

`https://view.cgi-dev.de/geoserver/wms/reflect?layers=osmgray:dark_bg&srs=EPSG:70203&format=application/openlayers#toggle`

`https://view.cgi-dev.de/geoserver/wms/reflect?layers=osmgray:dark_bg&srs=EPSG:70204&format=application/openlayers#toggle`

```
...
70203=PROJCS["equi7_antarctica_nofalseXY",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",3714266.97719],PARAMETER["false_northing",3402016.50625],PARAMETER["central_meridian",0.0],PARAMETER["latitude_of_origin",-90.0],UNIT["Meter",1.0]]
70204=PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",3714266.97719],PARAMETER["false_northing",3402016.50625],PARAMETER["central_meridian",0.0],PARAMETER["latitude_of_origin",-90.0],UNIT["Meter",1.0]]
...
```


![image](https://user-images.githubusercontent.com/5264230/91693689-b477ce80-eb6b-11ea-9799-4748a392b980.png)

```
2020-08-28 17:22:03,257 ERROR [geoserver.ows] -
org.geoserver.platform.ServiceException: Rendering process failed
at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:637)
at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:278)
at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:135)
at org.geoserver.wms.GetMap.executeInternal(GetMap.java:707)
at org.geoserver.wms.GetMap.run(GetMap.java:287)
at org.geoserver.wms.GetMap.run(GetMap.java:110)
at org.geoserver.wms.DefaultWebMapService.getMap(DefaultWebMapService.java:253)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.geoserver.kml.WebMapServiceKmlInterceptor.invoke(WebMapServiceKmlInterceptor.java:38)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:55)
at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:31)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:79)
at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:53)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:28)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy119.getMap(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:879)
at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:890)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:73)
at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:140)
at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.geoserver.security.GeoServerAuthenticationKeyFilter.doFilter(GeoServerAuthenticationKeyFilter.java:100)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:79)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:47)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2511)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error transforming bbox
at org.geotools.renderer.lite.StreamingRenderer.getStyleQuery(StreamingRenderer.java:1217)
at org.geotools.renderer.lite.StreamingRenderer.getFeatures(StreamingRenderer.java:2217)
at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2156)
at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:906)
at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:596)
... 124 more
Caused by: java.lang.NullPointerException
at org.geotools.renderer.lite.StreamingRenderer.getStyleQuery(StreamingRenderer.java:1146)
... 128 more
```

That looks like the same exception reported [here](https://github.com/geosolutions-it/eumetsat-EOWS/issues/356#issue-682543051)

Did I miss something in the build / deploy of the fix? The timestamp on geotools jars look ok
```
gt-app-schema-resolver-22-EOWS-20200828.164221-4.jar
gt-arcgrid-22-EOWS-20200828.163521-4.jar
gt-brewer-22-EOWS-20200828.164323-4.jar
gt-complex-22-EOWS-20200828.164226-4.jar
gt-coverage-22-EOWS-20200828.163236-4.jar
gt-coverage-api-22-EOWS-20200828.164009-4.jar
gt-cql-22-EOWS-20200828.163249-4.jar
gt-css-22-EOWS-20200828.164756-4.jar
gt-csv-22-EOWS-20200828.164815-4.jar
gt-epsg-hsql-22-EOWS-20200828.163052-4.jar
gt-feature-pregeneralized-22-EOWS-20200828.163848-4.jar
gt-geojson-22-EOWS-20200828.164608-4.jar
gt-geopkg-22-EOWS-20200828.164212-4.jar
gt-geotiff-22-EOWS-20200828.163303-4.jar
gt-grid-22-EOWS-20200828.164328-4.jar
gt-image-22-EOWS-20200828.163430-4.jar
gt-imagemosaic-22-EOWS-20200828.163500-4.jar
gt-jdbc-22-EOWS-20200828.163311-4.jar
gt-jdbc-h2-22-EOWS-20200828.163353-4.jar
gt-jdbc-oracle-22-EOWS-20200828.163357-4.jar
gt-jdbc-postgis-22-EOWS-20200828.163403-4.jar
gt-jdbc-sqlserver-22-EOWS-20200828.163934-4.jar
gt-main-22-EOWS-20200828.163122-4.jar
gt-metadata-22-EOWS-20200828.163016-4.jar
gt-netcdf-22-EOWS-20200828.164114-4.jar
gt-opengis-22-EOWS-20200828.163000-4.jar
gt-process-22-EOWS-20200828.164403-4.jar
gt-process-feature-22-EOWS-20200828.164528-4.jar
gt-process-geometry-22-EOWS-20200828.164612-4.jar
gt-process-raster-22-EOWS-20200828.164548-4.jar
gt-property-22-EOWS-20200828.163254-4.jar
gt-referencing-22-EOWS-20200828.163035-4.jar
gt-render-22-EOWS-20200828.163733-4.jar
gt-shapefile-22-EOWS-20200828.163418-4.jar
gt-svg-22-EOWS-20200828.163958-4.jar
gt-tile-client-22-EOWS-20200828.164349-4.jar
gt-transform-22-EOWS-20200828.163424-4.jar
gt-wfs-ng-22-EOWS-20200828.164648-4.jar
gt-wms-22-EOWS-20200828.164343-4.jar
gt-wmts-22-EOWS-20200828.164432-4.jar
gt-wps-22-EOWS-20200828.164732-4.jar
gt-xml-22-EOWS-20200828.163140-4.jar
gt-xsd-core-22-EOWS-20200828.163151-4.jar
gt-xsd-fes-22-EOWS-20200828.164201-4.jar
gt-xsd-filter-22-EOWS-20200828.163600-4.jar
gt-xsd-gml2-22-EOWS-20200828.163528-4.jar
gt-xsd-gml3-22-EOWS-20200828.163551-4.jar
gt-xsd-kml-22-EOWS-20200828.164439-4.jar
gt-xsd-ows-22-EOWS-20200828.164152-4.jar
gt-xsd-sld-22-EOWS-20200828.163609-4.jar
gt-xsd-wcs-22-EOWS-20200828.164502-4.jar
gt-xsd-wfs-22-EOWS-20200828.164453-4.jar
gt-xsd-wmts-22-EOWS-20200828.164356-4.jar
gt-xsd-wps-22-EOWS-20200828.164510-4.jar
```

**Comment by randomorder** [comment]
The config of the BBOX of one of the layers belonging to the layergroup was wrong
![image](https://user-images.githubusercontent.com/5264230/91699004-e856f200-eb73-11ea-8d2b-1386ee173da3.png)

It is working in DEV now
