### ISSUE TITLE
Another potentially harmful file listing in the importer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#376]
Apparently we have the importer do another file listing in a directory, see below...

"http-apr-8080-exec-8" #197 daemon prio=5 os_prio=0 tid=0x00007fee6434e800 nid=0xeb runnable [0x00007fed36cf9000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:1122)
	at java.io.File.listFiles(File.java:1207)
	at org.geoserver.importer.SpatialFile.prepare(SpatialFile.java:103)
	at org.geoserver.importer.Importer.addTasks(Importer.java:492)
	at org.geoserver.importer.Importer.init(Importer.java:460)
	at org.geoserver.importer.rest.ImportController.createImport(ImportController.java:224)
	at org.geoserver.importer.rest.ImportController.postImports(ImportController.java:73)
	at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

We have no details on what we are ingesting, but I would double check with the ingestion in a time enabled mosaic of a GeoTiff file placed in a directory with thousands of other files. If you can't replicate, let us know.

The incriminated line of code is [this]("http-apr-8080-exec-8" #197 daemon prio=5 os_prio=0 tid=0x00007fee6434e800 nid=0xeb runnable [0x00007fed36cf9000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:1122)
	at java.io.File.listFiles(File.java:1207)
	at org.geoserver.importer.SpatialFile.prepare(SpatialFile.java:103)
	at org.geoserver.importer.Importer.addTasks(Importer.java:492)
	at org.geoserver.importer.Importer.init(Importer.java:460)
	at org.geoserver.importer.rest.ImportController.createImport(ImportController.java:224)
	at org.geoserver.importer.rest.ImportController.postImports(ImportController.java:73)
	at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)) one.

**Comment by dromagnoli** [comment]
See related GeoServer ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9733

**Comment by dromagnoli** [comment]
Fix ready to be merged on master branch (some osgeo repo down at the moment making travis fail, it was green yesterday before updating a comment line).
Fix also ported to EOWS-158 branch

**Comment by simboss** [comment]
@dromagnoli has this been backported to 2.17?

Can we close this then?

**Comment by dromagnoli** [comment]
Yep
